ethereum_rpc = "https://rpc.hoodi.ethpandaops.io/"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps.mint_guard_v5]
path = "out/MintGuardTrap.sol/MintGuardTrap.json"
response_contract = "0x138C24E88cba835ddC926C4F466bBBa33Af9086f"
# This matches the Drosera Executor authorized in your Response contract
response_function = "respond(uint256)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 1
private_trap = false
address = "0xe9a97fcCDAea89921288B36Db011a57B17F02973"

# Removed collect_config to rely on the contract's internal collect()
